### ISSUE TITLE
Change nodeAffinity to not require master or control plane labels on nodes

### ISSUE THREAD

**Issue by bhpratt** [rh-ecosystem-edge/kernel-module-management#1438]
Some installations of managed OpenShift such as Hypershift: https://github.com/openshift/hypershift deploy a hosted control plane that is segmented from the data plane. In these installs, the worker nodes do not have the `node-role.kubernetes.io/control-plane` or `node-role.kubernetes.io/master` labels. Because the worker nodes do not have these labels, operators, such as the Kernel Module Management Operator that include `requiredDuringSchedulingIgnoredDuringExecution` such as:

```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
```

Will not run out of the box. Suggestion is to change the nodeAffinity to `preferredDuringSchedulingIgnoredDuringExecution` or expose a method for the end user to set their own nodeAffinity to accommodate these types of OpenShift installs.
